FROM digrouz/alpine-s6:latest
LABEL maintainer "DI GREGORIO Nicolas <nicolas.digregorio@gmail.com>"

ARG JACKETT_VERSION='0.22.1433'
ARG JACKETT_ARCH='AMDx64'

### Environment variables
ENV LANG='en_US.UTF-8' \
    LANGUAGE='en_US.UTF-8' \
    TERM='xterm' \
    XDG_DATA_HOME='/config' \
    XDG_CONFIG_HOME='/config' \
    JACKETT_VERSION="${JACKETT_VERSION}" \
    JACKETT_ARCH="${JACKETT_ARCH}"

### Copy config files
COPY root/ /

### Install Application
RUN set -x \
    apk upgrade --no-cache && \
    apk add --no-cache --virtual=build-deps \
      ca-certificates \
      curl \
    && \
    apk add --no-cache --virtual=run-deps \
      ca-certificates \
      gcompat \
      icu \
      icu-data-full \
      icu-libs \
      libintl \
      sqlite-libs \
    && \
    mkdir /opt/Jackett && \
    curl -SsL https://github.com/Jackett/Jackett/releases/download/v${JACKETT_VERSION}/Jackett.Binaries.LinuxMusl${JACKETT_ARCH}.tar.gz -o /tmp/jackett.tar.gz && \
    tar xzf /tmp/jackett.tar.gz -C /opt/Jackett --strip-components=1 && \
    echo "export XDG_CONFIG_HOME='${XDG_CONFIG_HOME}'" >> /etc/profile.d/docker-xdg.sh && \
    echo "${JACKETT_VERSION}-${JACKETT_ARCH}-digrouz" > /etc/docker-image && \
    chmod 0755 /opt/Jackett && \
    find /opt/Jackett -type d -exec chmod 0755 {} \; && \
    find /opt/Jackett -type f -exec chmod 0644 {} \; && \
    chmod 0755 /opt/Jackett/jackett && \
    apk del --no-cache --purge \
      build-deps  \
    && \
    rm -rf /tmp/* \
           /var/cache/apk/*  \
           /var/tmp/*

### Volume
Volume ["/config","/downloads"]

### Expose ports
Expose 9117

### Running User: not used, managed by docker-entrypoint.sh
#USER jackett

### Start jackett
ENTRYPOINT ["/init"]
