ARG JACKETT_VERSION='0.20.772'

FROM centos:7 AS su-exec-builder

RUN set -x && \
    yum update -y && \
    yum install -y \
      gcc \
      make \
      git \
    && \
    git clone --depth 1 https://github.com/ncopa/su-exec.git /opt/su-exec && \
    cd /opt/su-exec && \
    make

FROM centos:7
LABEL maintainer "DI GREGORIO Nicolas <nicolas.digregorio@gmail.com>"

ARG JACKETT_VERSION

### Environment variables
ENV LANG='en_US.UTF-8' \
    LANGUAGE='en_US.UTF-8' \
    TERM='xterm' \
    APPUSER='jackett' \
    APPUID='10008' \
    APPGID='10008' \
    XDG_DATA_HOME='/config' \
    XDG_CONFIG_HOME='/config' \
    JACKETT_VERSION="${JACKETT_VERSION}"
    
### Copy config files
COPY root/ /
COPY --from=su-exec-builder /opt/su-exec/su-exec /usr/local/bin/su-exec

### Install Application
RUN set -x && \
    chmod 1777 /tmp && \
    . /usr/local/bin/docker-entrypoint-functions.sh && \
    MYUSER="${APPUSER}" && \
    MYUID="${APPUID}" && \
    MYGID="${APPGID}" && \
    ConfigureUser && \
    yum install -y \
      epel-release \
    && \
    rpm --import "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF" && \
    curl https://download.mono-project.com/repo/centos7-stable.repo -o /etc/yum.repos.d/mono-centos7-stable.repo && \
    echo "export XDG_DATA_HOME='${XDG_DATA_HOME}'" > /etc/profile.d/docker-xdg.sh && \
    echo "export XDG_CONFIG_HOME='${XDG_CONFIG_HOME}'" >> /etc/profile.d/docker-xdg.sh && \
    yum update -y && \
    yum install -y \
      ca-certificates \
      libcurl \
      python \
      bash \
      mono-devel \
      wget \
    && \
    mozroots --import --sync && \
    mkdir -p /opt/Jackett && \
    curl -sSL https://github.com/Jackett/Jackett/releases/download/v${JACKETT_VERSION}/Jackett.Binaries.Mono.tar.gz -o /tmp/jacket.tar.gz && \
    tar xzf /tmp/jacket.tar.gz -C /opt && \
    chown -R "${MYUSER}":"${MYUSER}" /opt/Jackett  && \
    chmod 0755 /opt/Jackett  && \
    mkdir /docker-entrypoint.d && \
    chmod +x /usr/local/bin/docker-entrypoint.sh && \
    yum clean all && \
    ln -snf /usr/local/bin/docker-entrypoint.sh /docker-entrypoint.sh && \
    rm -rf /tmp/* \
           /var/cache/yum/*  \
           /var/tmp/*
    
### Volume
Volume ["/config","/downloads"]

### Expose ports
Expose 9117

### Running User: not used, managed by docker-entrypoint.sh
#USER jackett

### Start jackett
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["jackett-mono"]
