FROM alpine:3.16.2
LABEL maintainer "DI GREGORIO Nicolas <nicolas.digregorio@gmail.com>"

ARG JACKETT_VERSION='0.20.1903'

### Environment variables
ENV LANG='en_US.UTF-8' \
    LANGUAGE='en_US.UTF-8' \
    TERM='xterm' \
    APPUSER='jackett' \
    APPUID='10008' \
    APPGID='10008' \
    XDG_DATA_HOME='/config' \
    XDG_CONFIG_HOME='/config' \
    JACKETT_VERSION="${JACKETT_VERSION}"
    
### Copy config files
COPY root/ /

### Install Application
RUN set -x && \
    chmod 1777 /tmp && \
    . /usr/local/bin/docker-entrypoint-functions.sh && \
    MYUSER="${APPUSER}" && \
    MYUID="${APPUID}" && \
    MYGID="${APPGID}" && \
    ConfigureUser && \
    apk upgrade --no-cache && \
    apk add --no-cache --virtual=build-deps \
      ca-certificates \
      curl \
    && \
    apk add --no-cache --virtual=run-deps \
      libcurl \
      python3 \
      su-exec \
      bash \
    && \
    apk add --no-cache --repository http://nl.alpinelinux.org/alpine/edge/testing --virtual=run-deps-testing \
      mono \
    && \
    cert-sync /etc/ssl/certs/ca-certificates.crt && \
    echo "export XDG_DATA_HOME='${XDG_DATA_HOME}'" > /etc/profile.d/docker-xdg.sh && \
    echo "export XDG_CONFIG_HOME='${XDG_CONFIG_HOME}'" >> /etc/profile.d/docker-xdg.sh && \
    mkdir -p /opt/Jackett && \
    mkdir -p /home/"${MYUSER}"/.config && \
    curl -sSL https://github.com/Jackett/Jackett/releases/download/v${JACKETT_VERSION}/Jackett.Binaries.Mono.tar.gz -o /tmp/jackett.tar.gz && \
    tar xzf /tmp/jackett.tar.gz -C /opt && \
    chown -R "${MYUSER}":"${MYUSER}" /opt/Jackett /home/"${MYUSER}" && \
    chmod 0755 /opt/Jackett && \
    apk del --no-cache --purge \
      build-deps  \
    && \
    mkdir /docker-entrypoint.d && \
    chmod +x /usr/local/bin/docker-entrypoint.sh && \
    ln -snf /usr/local/bin/docker-entrypoint.sh /docker-entrypoint.sh && \
    rm -rf /tmp/* \
           /var/cache/apk/*  \
           /var/tmp/*
    
### Volume
Volume ["/config","/downloads"]

### Expose ports
Expose 9117

### Running User: not used, managed by docker-entrypoint.sh
#USER jackett

### Start jackett
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["jackett-mono"]
