name: dockerhub-workflow

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push tag alpine
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile_alpine-core
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/jackett:alpine
      -
        name: Build and push tag latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile_alpine-core
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/jackett:latest
      -
        name: Build and push tag alpine-core
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile_alpine-core
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/jackett:alpine-core
      -
        name: Build and push tag centos7-mono
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile_centos7-mono
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/jackett:centos7-mono
      -
        name: Build and push tag centos7
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile_centos7-mono
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/jackett:centos7

